update to use never versions

diff --git a/bin/install b/bin/install
--- a/bin/install
+++ b/bin/install
@@ -1,80 +1,69 @@
 #!/usr/bin/env bash
 
-# Documentation originally from: https://github.com/asdf-vm/asdf/blob/master/docs/plugins-create.md
-#
-# This script should install the version, in the path mentioned in ASDF_INSTALL_PATH.
-#
-# The install script should exit with a status of 0 when the installation is successful.
-# If the installation fails the script should exit with any non-zero exit status.
-#
-# If possible the script should only place files in the ASDF_INSTALL_PATH directory once
-# the build and installation of the tool is deemed successful by the install script.
-# asdf checks for the existence of the ASDF_INSTALL_PATH directory in order to determine
-# if that version of the tool is installed. If the ASDF_INSTALL_PATH directory is populated
-# at the beginning of the installation process other asdf commands run in other terminals
-# during the installation may consider that version of the tool installed,
-# even when it is not fully installed.
-
-set -e
-set -o pipefail
-
 github_coordinates="Shopify/ejson"
 tool_name="ejson"
+
+ASDF_INSTALL_TYPE=${ASDF_INSTALL_TYPE:-version}
+TMPDIR=${TMPDIR:-/tmp}
+[ -n "$ASDF_INSTALL_VERSION" ] || (>&2 echo 'Missing ASDF_INSTALL_VERSION' && exit 1)
+[ -n "$ASDF_INSTALL_PATH" ] || (>&2 echo 'Missing ASDF_INSTALL_PATH' && exit 1)
 
 install_tool() {
   local version=$2
   local install_path=$3
-  local tmp_download_dir=$4
-  local binary_name=$5
-
-  local platform
   local bin_install_path="$install_path/bin"
-  local binary_path="$bin_install_path/${binary_name}"
-  local download_url
-  local download_path
+  local filename; filename=$(get_filename "$version")
+  local download_url; download_url=$(get_download_url "$filename")
 
-  platform=$(get_platform)
-  download_url=$(get_download_url "$version" "$platform" "$binary_name")
-  download_path="$tmp_download_dir/"$(get_filename "$version" "$platform" "$binary_name")
-
-  echo "Downloading [${binary_name}] from ${download_url} to ${download_path}"
-  curl -Lo "$download_path" "$download_url"
-
-  echo "Creating bin directory"
   mkdir -p "${bin_install_path}"
 
-  echo "Cleaning previous binaries"
-  rm -f "$binary_path" 2>/dev/null || true
+  local bin_path="${bin_install_path}/${tool_name}"
+  echo "Downloading ${tool_name} from ${download_url}"
+  curl -sSL "$download_url" -o "${install_path}/${filename}.tar.gz"
+  tar xzf "${install_path}/${filename}.tar.gz" -C "${install_path}"
+  mv "${install_path}/${filename}"/* "${install_path}"
+  mv "${install_path}/${tool_name}" "${bin_path}"
+  chmod +x "$bin_path"
+  rm -rf "${install_path}/${filename}.tar.gz" "${install_path}/${filename}"
+}
 
-  echo "Copying binary"
-  cp "${download_path}" "${binary_path}"
-  chmod +x "${binary_path}"
+get_arch() {
+  uname -m | tr '[:upper:]' '[:lower:]'
 }
 
 get_platform() {
-  if [[ "$(uname)" == "Linux" ]]; then
-    echo "linux-amd64"
-  else
-    echo "darwin-amd64"
-  fi
+  uname | tr '[:upper:]' '[:lower:]'
+}
+
+get_release() {
+  case $(get_arch)-$(get_platform) in
+    arm64-darwin)
+      echo 'darwin_arm64' ;;
+    x86_64-darwin)
+      echo 'darwin_amd64' ;;
+    arm*-linux | aarch*-linux)
+      echo 'linux_arm64' ;;
+    x86_64-linux)
+      echo 'linux_amd64' ;;
+    i[3456]86-linux)
+      echo 'linux_386' ;;
+    x86_64-windows)
+      echo 'windows_amd64' ;;
+    i[3456]-windows)
+      echo 'windows_386' ;;
+    *)
+      echo "$(get_arch)-$(get_platform)"
+  esac
 }
 
 get_filename() {
-  local platform="$1"
-
-  echo "${platform}"
-}
+  local version="$1"
+  echo "${tool_name}_${version}_$(get_release)"
+} 
 
 get_download_url() {
-  local version="$1"
-  local platform="$2"
-  local binary_name="$3"
-  local filename
-  filename="$(get_filename "$platform")"
-
-  echo "https://github.com/${github_coordinates}/releases/download/v${version}/${filename}"
+  local filename="$1"
+  echo "https://github.com/${github_coordinates}/releases/download/v${version}/${filename}.tar.gz"
 }
 
-tmp_download_dir="$(mktemp -d -t 'asdf_XXXXXXXX')"
-trap 'rm -rf "${tmp_download_dir}"' EXIT
-install_tool "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH" "$tmp_download_dir" "${tool_name}"
+install_tool "$ASDF_INSTALL_TYPE" "$ASDF_INSTALL_VERSION" "$ASDF_INSTALL_PATH"
